go:
  version: 1.7.3
repository:
  path: github.com/jonnenauha/prometheus_varnish_exporter
build:
  flags: -a -tags netgo
  ldflags: |
    -X {{repoPath}}/vendor/github.com/prometheus/common/version.Version={{.Version}}
    -X {{repoPath}}/vendor/github.com/prometheus/common/version.Revision={{.Revision}}
    -X {{repoPath}}/vendor/github.com/prometheus/common/version.Branch={{.Branch}}
    -X {{repoPath}}/vendor/github.com/prometheus/common/version.BuildUser={{user}}@{{host}}
    -X {{repoPath}}/vendor/github.com/prometheus/common/version.BuildDate={{date "20060102-15:04:05"}}
tarball:
  files:
    - LICENSE
crossbuild:
  platforms:
    - darwin/386
    - darwin/amd64
    - freebsd/386
    - freebsd/amd64
    - linux/386
    - linux/amd64
    - netbsd/386
    - netbsd/amd64
    - openbsd/386
    - openbsd/amd64
    - windows/386
    - windows/amd64
